# Generated by Django 5.0.6 on 2024-05-28 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppBlog', '0004_remove_comment_user_comment_email_comment_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='typecategory',
            field=models.CharField(choices=[('World', 'World'), ('Technology', 'Technology'), ('Culture', 'Culture'), ('Business', 'Business'), ('Politics', 'Politics'), ('Science', 'Science'), ('Travel', 'Travel'), ('Health', 'Health')], default=1, max_length=255),
            preserve_default=False,
        ),
    ]
