# Generated by Django 5.0.6 on 2024-05-28 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppBlog', '0007_alter_blog_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='typecategory',
        ),
    ]
